### ISSUE TITLE
Install  wkhtmltopdf and Chinese Fonts

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-odoo#1]
**What type of your feature request?**  
solution refer to: Migrate https://github.com/Websoft9/role_wkhtmltopdf

**Comment by qiaofeng1227** [comment]
附带两点说明：
1. 不手动安装wkhtmltox时，容器里面有wkhtmltox的相关信息
2. odoo镜像制作用普通用户odoo，为了执行cmd，需要提权，增加了 user: root
